const darkJokes = [
  "I have a lot of jokes about unemployed people, but it doesn't matter. None of them work.",
  "I want to die peacefully in my sleep, just like my grandfather. Not screaming in terror like the passengers in his car.",
  "Give a man a plane ticket, and he flies for a day. Push a man out of a plane, and he flies for the rest of his life.",
  "My grief counselor died the other day. He was so good at his job, I didn’t even care.",
  "I was digging in our garden when I found a chest full of gold coins. I was about to run inside and tell my wife, but then I remembered why I was digging in the garden.",
  "Even people who are good for nothing have the capacity to bring a smile to your face. For instance, when you push them down the stairs.",
  "The doctor gave me one year to live, so I shot him. The judge gave me 15 years. Problem solved.",
  "My wife left a note on the fridge: 'This isn't working.' I'm not sure what she's talking about; the fridge is cold and the light stays on.",
  "I visited my friend at the hospital. He kept yelling, 'A positive! A positive!' I told him, 'I’m trying to be, buddy, but things look pretty grim.'",
  "I’ll never forget my Grandfather’s last words to me just before he died. 'Are you still holding the ladder?'",
  "What's the difference between a Ferrari and a pile of dead bodies? I don't have a Ferrari in my garage.",
  "My wife told me to go out and get something that makes her look sexy. So I brought home a bottle of vodka.",
  "I was walking past a cemetery today and saw a guy crouching behind a gravestone. 'Morning!' I said. He looked up and replied, 'No, just having a poo.'",
  "The other day, my wife asked me how many women I'd slept with. I told her, 'Only you, Darling. With all the others I was awake.'",
  "Why did the man miss the funeral? He wasn’t a mourning person.",
  "I’m sorry and I apologize mean the same thing. Except at a funeral.",
  "My grandfather has the heart of a lion and a lifetime ban from the local zoo.",
  "A man goes to a library and asks for a book on how to commit suicide. The librarian says, 'Forget it, you won't bring it back.'",
  "Dark humor is like food. Not everyone gets it.",
  "What is the difference between a person and a pizza? A pizza doesn't scream when you put it in the oven.",
  "My daughter asked me how victims of house fires are identified. I told her, 'Usually by the smell.'",
  "Today I saw a kid crying and asked where his parents were. I love working at the orphanage.",
  "What has four legs and one arm? A happy Pitbull.",
  "When I die, I want to go out just like my manager. Screaming 'I’m not done yet!' while everyone else ignores him.",
  "What's the best part about being a gravedigger? You get to work with people who don't talk back.",
  "Why don't orphans play baseball? They don't know where home is.",
  "As I get older, I remember all the people I lost along the way. Maybe a career as a tour guide wasn't for me.",
  "My son, who is into astronomy, asked me how stars die. 'Usually an overdose,' I told him.",
  "I have a joke about social distancing, but it's too long to tell in person.",
  "I asked my dog, 'What’s on top of the house?' He said, 'Roof!' Then I asked, 'Who’s the greatest baseball player ever?' He said, 'Ruth!' Then I asked, 'What’s the texture of sandpaper?' He said, 'Rough!' He’s still a dog, but his career in stand-up is failing.",
  "What’s the difference between a light bulb and a pregnant woman? You can unscrew a light bulb.",
  "I saw an ad in the paper that said: 'Television for sale, $1, volume stuck on high.' I thought, 'I can’t turn that down!'",
  "My wife told me that if I didn't stop acting like a flamingo, she'd leave me. I had to put my foot down.",
  "The guy who stole my diary just died. My thoughts are with his family.",
  "I didn't think my mom's funeral would be this emotional, but she was always the life of the party.",
  "Why was the skeleton lonely? Because he had no body to talk to.",
  "I told my doctor that I broke my arm in two places. He told me to stop going to those places.",
  "My wife and I have reached the difficult decision that we do not want children. If anybody does, please just send me your contact details and we can drop them off tomorrow.",
  "Cemetery gates are only locked at night because people are dying to get in.",
  "What's the difference between a joke and a dark joke? A dark joke doesn't have a punchline, it has a body count.",
  "My elderly neighbor fell down the stairs today. I laughed so hard I almost fell down mine.",
  "What did the cannibal get when he was late for dinner? The cold shoulder.",
  "My wife said she wanted more space. So I locked her out of the house.",
  "You don’t need a parachute to go skydiving. You need a parachute to go skydiving twice.",
  "Why did the scarecrow win an award? Because he was outstanding in his field. Why did the farmer win an award? Because he buried the scarecrow there.",
  "I was born with a silver spoon in my mouth. My parents were very surprised when the X-ray came back.",
  "A guy walks into a bar with a shotgun. He yells, 'Who slept with my wife?' A guy in the back stands up and says, 'You haven't got enough ammo, mate.'",
  "I once saw a sign that said: 'Watch for children.' I thought, 'That sounds like a fair trade.'",
  "How many emo kids does it take to change a lightbulb? None, they all sit in the dark and cry.",
  "My ex-wife was hit by a bus yesterday. I've never been so happy that I drive a bus for a living.",
  "I got a job as a historian. I figured there was no future in it.",
  "I’m writing a book about all the people I’ve slept with. It’s a coloring book.",
  "Why do cemeteries have fences? Because people are dying to get in.",
  "What’s the last thing that goes through a bug’s mind as it hits the windshield? Its butt.",
  "I just read that someone gets stabbed in London every 52 seconds. Poor guy.",
  "I hate it when people ask me where I see myself in five years. I don’t even have 20/20 vision.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why did the blind man fall into the well? Because he couldn't see that well.",
  "What’s the difference between a hippo and a Zippo? One is really heavy, and the other is a little lighter.",
  "My boss told me to have a good day. So I went home.",
  "The only thing my father ever gave me was his name. And even then, he spelled it wrong on the birth certificate.",
  "I tried to catch some fog earlier. I mist.",
  "My teacher told me I'd never amount to anything because I procrastinate too much. I told her, 'Just you wait!'",
  "How do you make a tissue dance? You put a little boogey in it. How do you make a child cry? I've got plenty of ways.",
  "I used to be a baker, but I couldn't make enough dough.",
  "The doctor told me I was going deaf. It was hard to hear.",
  "I used to have a handle on life, but then it broke.",
  "What’s the difference between a teacher and a large pizza? A large pizza can feed a family of four.",
  "My wife told me she was going to leave me if I didn't stop being so dramatic. I looked her in the eyes and whispered, 'The end is near.'",
  "I’m on a whiskey diet. I’ve lost three days already.",
  "Why did the chicken cross the road? To get to the other side. Why did the suicidal man cross the road? To get to the other side.",
  "I have a great joke about time travel, but you didn't like it.",
  "I told my psychiatrist that I have suicidal tendencies. He told me from now on I have to pay in advance.",
  "What is the difference between a ginger and a brick? A brick gets laid.",
  "I’m friends with 25 letters of the alphabet. I don’t know Y.",
  "Why was the math book sad? Because it had too many problems.",
  "A man is holding a gun to my head and demands I tell him a joke. I said, 'My life.' He laughed and pulled the trigger.",
  "I don’t suffer from insanity. I enjoy every minute of it.",
  "Why did the baby cross the road? Because it was stapled to the chicken.",
  "I bought my friend a fridge for his birthday. I can't wait to see his face light up when he opens it.",
  "Why do they put bells on mental asylums? Because the inhabitants are all 'ding-a-lings'.",
  "I’m reading a book on anti-gravity. It’s impossible to put down.",
  "What do you call a cheap circumcision? A rip-off.",
  "I want to die on my 100th birthday, shot by a jealous husband.",
  "Life is like a box of chocolates. It doesn't last long if you're fat.",
  "What's the difference between a girlfriend and a wife? 45 pounds.",
  "I haven't slept for ten days. Because that would be too long.",
  "If at first you don't succeed, then skydiving isn't for you.",
  "I like my coffee like I like my magic. Dark.",
  "What do you call a dog with no legs? It doesn't matter, it's not coming anyway.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "What’s red and bad for your teeth? A brick.",
  "My doctor told me I need to stop masturbating. I asked him why, and he said, 'Because I’m trying to examine you.'",
  "Where did Mary go after the explosion? Everywhere.",
  "I was going to tell a dead baby joke, but I decided to leave it alone. It was already starting to smell.",
  "What's the difference between a bowling ball and a child? You can't fit a bowling ball in a microwave.",
  "My wife asked me why I carry a gun in the house. I said, 'Decepticons.' She laughed, I laughed, the toaster laughed. I shot the toaster.",
  "My girlfriend is like the square root of -100. A solid 10, but also imaginary.",
  "I have a lot of jokes about people with dementia, but I can't remember any of them.",
  "What’s the difference between a truckload of bowling balls and a truckload of dead babies? You can’t use a pitchfork on bowling balls.",
  "Why did the orphan go to the park? To play on the swings. Why did he fall off? Because he had no arms."
];

export { darkJokes };